### PR TITLE
Save and restore main window position and dimensions

### PR DESCRIPTION
**Pull request by robert-hoff**
Save and restore VRF window position and size between application runs

### CODE REVIEW

**Comment by xPaw** [comment]
Does this need to handle maximized state separately?

**Comment by robert-hoff** [comment]
Yea we probably need to handle it separately - I'll look into it. I realised also it would be a good idea to do checks against the available screensize because if VRF was closed on a separate monitor it can happen that it becomes placed outside the available xy space

**Comment by robert-hoff** [comment]
This should be a bit more general - I found that to get the window to restore to the last normal position (from a maximized state) the settings need to be applied after the form has been rendered, so I transferred the code into the OnShown() method

**Comment by xPaw** [comment]
Merged in master

**Pull request closed without merging**
