### PR TITLE
Implement BPTC (BC6H and BC7) textures decoding

### PR DESCRIPTION
**Pull request by lewa-j**
Before: 
before
After:
after

PS: I was not able to look at HL:Alyx lightmaps, so i fixed it.

### CODE REVIEW

**Comment by xPaw** [comment]
Nice! Did you bring this code from elsewhere or did you write it?

**Comment by lewa-j** [comment]
Lots of specifications reading and coffee. Spent it all weekend.

**Comment by xPaw** [comment]
Thanks!

**Comment by Marlamin** [comment]
Very cool!

**Pull request merged**
